import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Suspense } from "react";
import ScaleLoader from "react-spinners/ScaleLoader";
import Image from "next/image";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Solvro Coctails Frontend Solution",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-auto`}
			>
				<header className="text-center p-5 bg-accent">
					<div className="flex mx-auto w-fit text-white font-bold text-2xl align-middle sm:text-4xl">
						<Image
							src="/logo.png"
							alt="Solvro logo"
							width={100}
							height={100}
							className="w-20 h-20"
						/>
						<p className="pt-1 ml-2 sm:pt-4 sm:ml-5">
							Solvro Coctails Frontend Solution
						</p>
					</div>
				</header>
				<main className="pb-20">
					<Suspense
						fallback={
							<ScaleLoader
								className="w-fit h-[100vh] mx-auto my-[40vh]"
								color="#0d0df2"
							/>
						}
					>
						{children}
					</Suspense>
				</main>
				<footer className="w-screen fixed bottom-0 text-center bg-accent h-fit">
					<p className="bg-inherit py-5 text-white">
						Developed by{" "}
						<Link
							href="https://github.com/GTR1701"
							className="bg-inherit text-muted"
						>
							Dawid Kowal
						</Link>
					</p>
				</footer>
			</body>
		</html>
	);
}
