import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-auto`}
			>
				<header className="text-center p-5 bg-accent text-white font-bold text-xl">
					Solvro Coctails Frontend Solution
				</header>
				<main className="pb-20">{children}</main>
				<footer className="w-screen fixed bottom-0 text-center bg-accent h-fit">
					<p className="bg-inherit py-5 text-white">
						Developed by{" "}
						<Link
							href="https://github.com/GTR1701"
							className="bg-inherit text-muted"
						>
							Dawid Kowal
						</Link>
					</p>
				</footer>
			</body>
		</html>
	);
}
